-- 코드를 작성해주세요
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
  FROM DEVELOPERS AS D
 INNER JOIN SKILLCODES AS S
    ON D.SKILL_CODE & S.CODE
 WHERE S.NAME IN ('Python', 'C#')
 GROUP BY ID, EMAIL, FIRST_NAME, LAST_NAME
 ORDER BY ID ASC
 